listeners:
  - https: true
    bind_addr: ":8080"
  # - bind_addr: ":8081"

frontends:
  pandora.com:
    backends:
      - addr: "pandora.com"
  rdio.com:
      backends:
      - addr: "rdio.com"
  2ip.ru:
      backends:
      - addr: "178.63.151.224"
  www.whatismyip.com:
      backends:
      - addr: "www.whatismyip.com"
  '*.2ip.ru':
    backends:
      - addr: "178.63.151.224"
